add segbuf to quadgkjl
SciML/Integrals.jl pull request #151
Opened 2023-02-22 04:59 UTC by lxvm

Sometimes `quadgk` is used in the inner loop of a larger calculation (such as a nested integral) and it is desirable to reduce the number of allocations it makes. This pr adds a `segbuf` field to the `QuadGKJL` algorithm to allow the user to pass in a segment buffer that reduces the amount of memory allocated by the routine when reused across calls with compatible domain, integral, and error types.

```
julia> using Integrals, QuadGK

julia> g(x, (k,)) = sin(k*x)
g (generic function with 1 method)

julia> alg = QuadGKJL(; segbuf=QuadGK.alloc_segbuf(Float64, Float64, Float64))
QuadGKJL{typeof(LinearAlgebra.norm), Vector{QuadGK.Segment{Float64, Float64, Float64}}}(7, LinearAlgebra.norm, QuadGK.Segment{Float64, Float64, Float64}[QuadGK.Segment{Float64, Float64, Float64}(0.0, 0.0, 0.0, 0.0)])

julia> solve(IntegralProblem(g, 0, 1, 80.0), QuadGKJL(; segbuf=QuadGK.alloc_segbuf(Float64, Float64, Float64)))^C

julia> @allocated solve(IntegralProblem(g, 0, 1, 80.0))
2800

julia> @allocated solve(IntegralProblem(g, 0, 1, 80.0), alg)
1072
```

2023-03-08 13:32 UTC, ChrisRackauckas commented
I would think this would be best to do at `init!` time?

2023-03-14 13:05 UTC, ArnoStrouwen requested changes

2023-03-14 13:05 UTC, ArnoStrouwen commented on src/algorithms.jl
> +    segbuf::S
Need to add the keyword to the docstring.

2023-03-14 13:08 UTC, ArnoStrouwen commented
I think this is what is meant by init:
https://docs.sciml.ai/SciMLBase/stable/interfaces/Init_Solve/#init-and-the-Iterator-Interface
Currently this is not set up properly in Integrals.jl, but should be added.

2023-03-16 10:14 UTC, ChrisRackauckas commented
> It seems like I could close this pr and open a new one for properly providing the init interface as soon as I have some time for it

Yeah I think this is probably the right direction here. In the end, we really just need the `init` part of the interface in this package, and then need to just cache everything.

2023-03-16 10:14 UTC, closed without merging